site_name(HOST_NAME)
set(CONFIG_NAME "${HOST_NAME}-clang@apple-mp" CACHE PATH "")
message("CONFIG_NAME = ${CONFIG_NAME}")

set(CMAKE_C_COMPILER "/usr/bin/clang" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/usr/bin/clang++" CACHE PATH "")
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)

set(ENABLE_MPI ON CACHE PATH "")
set(MPI_C_COMPILER "/opt/homebrew/bin/mpicc" CACHE PATH "")
set(MPI_CXX_COMPILER "/opt/homebrew/bin/mpicxx" CACHE PATH "")
set(MPIEXEC "/opt/homebrew/bin/mpirun" CACHE PATH "")

set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "" FORCE)


set(ENABLE_CUDA "OFF" CACHE PATH "" FORCE)
set(ENABLE_OPENMP "OFF" CACHE PATH "" FORCE)

set(ENABLE_CALIPER "OFF" CACHE PATH "" FORCE )

set(SHIVA_BUILD_OBJ_LIBS ON CACHE BOOL "" FORCE)

