

#pragma once

#define SHIVA_VERSION_MAJOR 0

#define SHIVA_VERSION_MINOR 1

#define SHIVA_VERSION_PATCHLEVEL 0

/* #undef SHIVA_USE_CUDA */

/* #undef SHIVA_USE_HIP */

/* #undef SHIVA_USE_CALIPER */

#define SHIVA_USE_CAMP

#define SHIVA_USE_BOUNDS_CHECK

#define SHIVA_CUDA_MAJOR        0
#define SHIVA_CUDA_MINOR        0
#define SHIVA_CUDA_PATCHLEVEL   0
#define SHIVA_CUDA_VERSION_INT  0
